### ISSUE TITLE
Modules tree cleanup

### ISSUE THREAD

**Issue by paweljozwicki** [websight-io/kyanite#145]
Create a module `extensions` in `application` module and move `bulma-table-service` and `bulma-table-view` to this new submodule.

In case of more extensions it will be better to keep them in separated submodule.

**Comment by Rafal-DS** [comment]
Created a PR:
https://github.com/websight-io/bulma/pull/167

**Comment by michalcukierman** [comment]
Make sure to update README.MD

**Comment by Rafal-DS** [comment]
> Make sure to update README.MD

Done.
