### ISSUE TITLE
Level Item component has text centered if it's directly in Level component

### ISSUE THREAD

**Issue by paweljozwicki** [websight-io/kyanite#164]
The Level Item component has always been text-centered if it's directly in the Level component.

**Steps to reproduce**
1. Go to Bulma page
2. Add Level component
3. Add Level item component to Level component
4. Add Container and Title or Content component

**Current result**
The text is centered and there is no option to change that

**Expected behavior**
Possibility to have text aligned to the left.

**Screenshots**
<img width="1622" alt="Screenshot 2023-04-18 at 10 50 36" src="https://user-images.githubusercontent.com/109656376/232725235-76e4a8cc-56ed-4f90-81be-8d43d3e2b021.png">

**Comment by Rafal-DS** [comment]
Added a PR: https://github.com/websight-io/bulma/pull/171
