### ISSUE TITLE
Improve breadcrumb component

### ISSUE THREAD

**Issue by paweljozwicki** [websight-io/kyanite#81]
As an author, I want to have the possibility to choose an icon for the Breadcrumb element

Technical details:
- there are a few other places where icons are used. Verify the possibility of moving some wider parts of dialogs to commons and include it in all the places.

**Comment by gfazek** [comment]
This issue is blocked by https://github.com/websight-io/starter/issues/63.

**Comment by paweljozwicki** [comment]
Blocking issue was resolved in [WebSight CMS 1.11.1](https://www.websight.io/docs/release-notes/websight-cms/#1111-march-21-2023)
